networks:
  common_net:

volumes:
  postgres:
  pgadmin:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - common_net

  backend:
    build:
      context: ./backend
    networks:
      - common_net
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    networks:
      - common_net
  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_pass
    networks:
      - common_net

  admin:
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: changeme@mail.mm
      PGADMIN_DEFAULT_PASSWORD: changemepass
    ports:
      - "15132:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - common_net