networks:
  common_net:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - common_net

  backend:
    build:
      context: ./backend
    networks:
      - common_net
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    networks:
      - common_net
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080